export default DATA =
[
    {"id":1,
    "brand":"Ray-Ban",
    "image":"http://dummyimage.com/224x100.png/5fa2dd/ffffff",
    "price":72,
    "type":"Sunglasses",
    "description":"Elevate your style with these sleek and trendy sunglasses. Designed to protect your eyes while making a fashion statement.",
    "specifications":""},
    
    {"id":2,
    "brand":"Gucci",
    "image":"http://dummyimage.com/155x100.png/dddddd/000000",
    "price":56,
    "type":"Sunglasses",
    "description":"Indulge in luxury with these designer sunglasses. Crafted with precision and style, they're the epitome of elegance and sophistication.",
    "specifications":""},
    
    {"id":3,
    "brand":"Calvin Klein",
    "image":"http://dummyimage.com/128x100.png/5fa2dd/ffffff",
    "price":20,
    "type":"Glasses",
    "description":"Embrace a sophisticated look with these elegant glasses. Designed for both style and functionality, they bring a touch of refinement to any outfit.",
    "specifications":""},
    
    {"id":4,
    "brand":"Versace",
    "image":"http://dummyimage.com/237x100.png/cc0000/ffffff",
    "price":82,
    "type":"Sunglasses",
    "description":"Step into the world of high-end fashion with these iconic sunglasses from Versace. Their sleek design and impeccable craftsmanship make them a symbol of refined style.",
    "specifications":""},
    
    {"id":5,
    "brand":"Police",
    "image":"http://dummyimage.com/212x100.png/cc0000/ffffff",
    "price":54,
    "type":"Sunglasses",
    "description":"Get ready for summer with these cool and comfortable sunglasses. Whether you're lounging by the pool or exploring the city, they're the perfect companion.",
    "specifications":""},
    
    {"id":6,
    "brand":"Carrera",
    "image":"http://dummyimage.com/188x100.png/dddddd/000000",
    "price":12,
    "type":"Sunglasses",
    "description":"Shield your eyes from the sun in style with these chic sunglasses. Their unique frame and tinted lenses add a touch of sophistication to any outfit.",
    "specifications":""},
    
    {"id":7,
    "brand":"Fendi",
    "image":"http://dummyimage.com/108x100.png/dddddd/000000",
    "price":84,
    "type":"Sunglasses",
    "description":"Experience the epitome of luxury with these exquisite sunglasses from Fendi. Meticulously crafted with the finest materials, they exude elegance and sophistication.",
    "specifications":""},
    
    {"id":8,
    "brand":"Tom Ford",
    "image":"http://dummyimage.com/165x100.png/cc0000/ffffff",
    "price":4,
    "type":"Glasses",
    "description":"Achieve a smart and polished look with these sleek glasses. Whether for work or play, they add a touch of professionalism to your ensemble.",
    "specifications":""},
    
    {"id":9,
    "brand":"Tom Tailor",
    "image":"http://dummyimage.com/104x100.png/cc0000/ffffff",
    "price":53,
    "type":"Glasses",
    "description":"See the world through a new lens with these trendy glasses. Their modern frame and comfortable fit make them perfect for everyday wear.",
    "specifications":""},
    
    {"id":10,
    "brand":"Giorgio Armani",
    "image":"http://dummyimage.com/168x100.png/cc0000/ffffff",
    "price":44,
    "type":"Glasses",
    "description":"Discover timeless elegance with these classic glasses. Their timeless silhouette and versatile style make them a perfect accessory for any occasion.",
    "specifications":""}
    ]