export default DATA =
[
    {"id":1,
    "brand":"Ray-Ban",
    "image":["https://cdna.lystit.com/520/650/n/photos/ruelala/40d264ac/ray-ban-Brown-Clubmaster-Classic-51mm-Sunglasses.jpeg",
            "https://cdna.lystit.com/520/650/n/photos/ruelala/40ad0d0c/ray-ban-Brown-Clubmaster-Classic-51mm-Sunglasses.jpeg"
            ],
    "price":155,
    "type":"Sunglasses",
    "description":"Elevate your style with these sleek and trendy sunglasses. Designed to protect your eyes while making a fashion statement.",
    "specifications":""},
    
    {"id":2,
    "brand":"Gucci",
    "image":["https://cdna.lystit.com/520/650/n/photos/ruelala/9a820920/gucci-Black-GG1174S-54mm-Sunglasses.jpeg",
             "https://cdna.lystit.com/520/650/n/photos/ruelala/0be16bbd/gucci-Black-GG1174S-54mm-Sunglasses.jpeg" 
            ],
    "price":140,
    "type":"Sunglasses",
    "description":"Indulge in luxury with these designer sunglasses. Crafted with precision and style, they're the epitome of elegance and sophistication.",
    "specifications":""},
    
    {"id":3,
    "brand":"Saint Laurent",
    "image":["https://cdna.lystit.com/520/650/n/photos/ruelala/e3a8ba66/saint-laurent-Brown-Unisex-Sl365dylan-53mm-Sunglasses.jpeg",
            "https://cdna.lystit.com/520/650/n/photos/ruelala/dd55f441/saint-laurent-Brown-Unisex-Sl365dylan-53mm-Sunglasses.jpeg"],
    "price":110,
    "type":"Sunglasses",
    "description":"Get ready for summer with these cool and comfortable sunglasses. Whether you're lounging by the pool or exploring the city, they're the perfect companion.",
    "specifications":""},
    
    {"id":4,
    "brand":"Versace",
    "image": ["https://cdna.lystit.com/520/650/n/photos/ruelala/54ece2ed/versace-Brown-Ve4430u-53mm-Sunglasses.jpeg",
            "https://cdna.lystit.com/520/650/n/photos/ruelala/cc36ea1e/versace-Brown-Ve4430u-53mm-Sunglasses.jpeg"
    ],
    "price":92,
    "type":"Sunglasses",
    "description":"Step into the world of high-end fashion with these iconic sunglasses from Versace. Their sleek design and impeccable craftsmanship make them a symbol of refined style.",
    "specifications":""},
    
    {"id":5,
    "brand":"Givenchy",
    "image":["https://cdna.lystit.com/520/650/n/photos/gilt/6db8ced4/givenchy-Gold-Gv-0120-49mm-Optical-Frames.jpeg",
            "https://cdna.lystit.com/520/650/n/photos/gilt/2fa3d7d5/givenchy-Gold-Gv-0120-49mm-Optical-Frames.jpeg"],
    "price":355,
    "type":"Glasses",
    "description":"Embrace a sophisticated look with these elegant glasses. Designed for both style and functionality, they bring a touch of refinement to any outfit.",
    "specifications":""},
    
    {"id":6,
    "brand":"Carrera",
    "image":["https://cdna.lystit.com/520/650/n/photos/ruelala/776b5cb5/carrera-Black-Unisex-60mm-Sunglasses.jpeg",
            "https://cdna.lystit.com/520/650/n/photos/gilt/2c19fba4/carrera-Black-60mm-Sunglasses.jpeg"],
    "price":95,
    "type":"Sunglasses",
    "description":"Shield your eyes from the sun in style with these chic sunglasses. Their unique frame and tinted lenses add a touch of sophistication to any outfit.",
    "specifications":""},
    
    {"id":7,
    "brand":"Fendi",
    "image":["https://cdna.lystit.com/520/650/n/photos/cettire/547e9d82/fendi-Grey-Square-Frame-Sunglasses.jpeg",
            "https://cdna.lystit.com/520/650/n/photos/cettire/286f37b2/fendi-Grey-Square-Frame-Sunglasses.jpeg"],
    "price":90,
    "type":"Sunglasses",
    "description":"Experience the epitome of luxury with these exquisite sunglasses from Fendi. Meticulously crafted with the finest materials, they exude elegance and sophistication.",
    "specifications":""},
    
    {"id":8,
    "brand":"Tom Ford",
    "image":["https://cdna.lystit.com/520/650/n/photos/ssense/e8c7b2a4/tom-ford-BLACK-Square-Glasses.jpeg",
            "https://cdna.lystit.com/520/650/n/photos/ssense/2b3bd4be/tom-ford-BLACK-Square-Glasses.jpeg"],
    "price":420,
    "type":"Glasses",
    "description":"Achieve a smart and polished look with these sleek glasses. Whether for work or play, they add a touch of professionalism to your ensemble.",
    "specifications":""},
    
    {"id":9,
    "brand":"Balenciaga",
    "image":["https://cdna.lystit.com/520/650/n/photos/gilt/20bbd090/balenciaga-Shiny-Black-Bb0098s-60mm-Sunglasses.jpeg",
            "https://cdna.lystit.com/520/650/n/photos/gilt/b05b8c4a/balenciaga-Shiny-Black-Bb0098s-60mm-Sunglasses.jpeg"],
    "price":110,
    "type":"Sunglasses",
    "description":"Elevate your style with Balenciaga sunglasses, the epitome of sophistication and trend-setting fashion. Crafted with meticulous attention to detail, these iconic shades exude confidence and glamour, ensuring you stand out from the crowd.",
    "specifications":""},
    
    {"id":10,
    "brand":"Giorgio Armani",
    "image":["https://cdna.lystit.com/520/650/n/photos/ssense/bb0f4cee/giorgio-armani-BLACK-Square-Glasses.jpeg",
            "https://cdna.lystit.com/520/650/n/photos/ssense/7201f779/giorgio-armani-BLACK-Square-Glasses.jpeg"],
    "price":250,
    "type":"Glasses",
    "description":"Discover timeless elegance with these classic glasses. Their timeless silhouette and versatile style make them a perfect accessory for any occasion.",
    "specifications":""}
    ]