export default Users =
[
    {"id":1,"first_name":"Nanete","last_name":"Skowcraft","email":"nskowcraft0@livejournal.com","token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJhYmNkMTIzIiwiZXhwaXJ5IjoxNjQ2NjM1NjExMzAxfQ.3Thp81rDFrKXr3WrY1MyMnNK8kKoZBX9lg-JwFznR-M","is_auth":true},
    {"id":2,"first_name":"Dillon","last_name":"Broadberrie","email":"dbroadberrie1@tumblr.com","token":"eyJ0eXAiOiJKV1QKbasjsGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJhYmJhDacIzIiwiZXhwaXJ5IjoxNjQ2NjM1NjExMzAxfQ.3Thp81rDFrKXr3WrY1MyMnNK8kKoZBX9lg-JwFznR-M","is_auth":false},
    {"id":3,"first_name":"Donnie","last_name":"Thewlis","email":"dthewlis2@ning.com","token":"rtvAsyAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJhYmNkMTIzIiwiZXhwaXJ5IjoxNjQ2NjM1kmdsmEQzAxfQ.3Thp81rDFrKXr3WrY1MyMnNK8kKoZBX9lg-JwFznR-M","is_auth":true},
    {"id":4,"first_name":"Madel","last_name":"Artis","email":"martis3@wordpress.com","token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiasaGafYmNkMTIzIiwiZXhwaXJ5IjoxNjQ2NjM1NjExMzAxfQ.3Thp81rDFrKXr3WrY1MyMnNK8kKoZBX9lg-JwFznR-A","is_auth":false},
    {"id":5,"first_name":"Freda","last_name":"Offield","email":"foffield4@biglobe.ne.jp","token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJhYmNkMTIzIiwiZXhwaXJ5IjdasmkasAt2NjM1NjExMzAxfQ.3Thp81rDFrKXr3WrY1MyMnNK8kKoZBX9lg-JwFznR-M","is_auth":false},
    {"id":6,"first_name":"Abey","last_name":"Weale","email":"aweale5@umich.edu","token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1dsa5AtySWQiOiJhYmNkMTIzIiwiZXhwaXJ5IjAnshmNjM1NjExMzAxfQ.3Thp81rDFrKXr3WrY1MyMnNK8kKoZBX9lg-JwFznR-M","is_auth":false},
    {"id":7,"first_name":"Toma","last_name":"Igoe","email":"tigoe6@yandex.ru","token":"yb6raeXAiOiJKV1QiLCJhbGciOiJIkfsdOiiJ9.eyJ1c2VySWQiOiJhYmNkMTIzIiwiZXhwaXJ5IjoxNjQ2NjM1NjExMzAxfQ.3Thp81rDFrKXr3WrY1MyMnNK8kKoZBX9lg-JwFznR-M","is_auth":true},
    {"id":8,"first_name":"Sargent","last_name":"Fenwick","email":"sfenwick7@jigsy.com","token":"eyJ0eXAiOiJKV1QiLCJaYtzhiOiJIUzI1NiJ9.eyJ1c2VySWQiOiJhYmNkMTIzIiwiZXhwaXJ5IjoxNjQ2NjM1NjExMzAxfQ.3Thp81rDFrKXr3WrY1MyMnNK8kKoZBX9lg-JwFznR-M","is_auth":false},
    {"id":9,"first_name":"Ole","last_name":"Constantinou","email":"oconstantinou8@adobe.com","token":"ehabAXAiOiJKV1QiLCJhbGciOiJIUzI1NiN3.eyJ1c2VySWQiOkmsakaAIzIiwiZXhwaXJ5IjoxNjQ2NjM1NjExMzAxfQ.3Thp81rDFrKXr3WrY1MyMnNK8kKoZBX9lg-JwFznR-M","is_auth":false},
    {"id":10,"first_name":"Luigi","last_name":"Hush","email":"lhush9@house.gov","token":"eyJ0eXAiOiJLOpavahbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJhYmNkMTIzIiwiZXhwaXJ5IjoxNjQ2NjM1NjExMzAxfQ.3Thp81rDFrKXr3WrY1MyMnNK8kKoZBX9lg-JwFznR-M","is_auth":false}
]